### PR TITLE
Informatics points

### PR DESCRIPTION
**Pull request by draikhert**
Added 23/24 journal
Fixed points

Co-authored-by: @draikhert draikhert@gmail.com
Co-authored-by: @worthant worthant@gmail.com

### CODE REVIEW

**Review by owl-from-hogvarts — APPROVED** [review]
LGTM

**Comment by owl-from-hogvarts** [comment]
For future. Commit messages should comply to [standard](https://github.com/Imtjl/.github/blob/main/CONTRIBUTING.md#commit-messages)

**Review by worthant — COMMENTED** [review]
1) You have 2 literally same commits, you can `squash` them (in interactive git rebase)
2) You should follow our commit convention (@owl-from-hogvarts mentioned it in the message above)

**Comment by worthant** [comment]
I fixed commits via `interactive rebase` (**git rebase -i informatics-points~3**)

**Pull request merged**
